CREATE TABLE Users (
	userNumber BIGINT PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(20) NOT NULL,
	ssn VARCHAR(7) NOT NULL,
	phone VARCHAR(13) NOT NULL,
	userId VARCHAR(16) NOT NULL,
	pw VARCHAR(20) NOT NULL,
	addr VARCHAR(25) NOT NULL
)AUTO_INCREMENT = 1;

SELECT * FROM Users;

DROP TABLE Users;

INSERT INTO Users (name, ssn, phone, userId, pw, addr)
VALUES('이태영', '970312', '010-2881-2498', 'lty', '1234', 'daegu');